apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: quiz-completed-subscription
  namespace: default
spec:
  pubsubname: learnpybyai-pubsub
  topic: quiz-completed
  routes:
    default: /webhooks/quiz-completed
  deadLetterTopic: quiz-completed-deadletter
  scopes:
  - progress-agent
  bulkSubscribe:
    enabled: false
