apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: struggle-alerts-subscription
  namespace: default
spec:
  pubsubname: learnpybyai-pubsub
  topic: struggle-alerts
  routes:
    default: /webhooks/struggle-alert
  deadLetterTopic: struggle-alerts-deadletter
  scopes:
  - teacher-service
  bulkSubscribe:
    enabled: false
